Importing libraries

In [1]:
import pandas as pd
import numpy as np

## Exploring the data

In [2]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

* printing keys of the dataset

In [3]:
print("Keys of iris dataset: \n{}".format(iris_dataset.keys()))

Keys of iris dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


* The value of the key DESCR is a short description of the dataset, as follows

In [4]:
val = iris_dataset['DESCR']
start_val = val[:200]     # slicing the string
print(start_val + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


* Target names are the targets to which the data is to be classified

In [5]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


* Features are the parameters of classification (these data are taken)

In [6]:
print("Feature names: {}".format(iris_dataset['feature_names']))

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


* Type of data is how the data is stored.
In this case it is stored as numpy ndarray.

In [7]:
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


* Shape of data gives an idea about data points and features(no of rows and columns the data have).

In [8]:
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


* Features for first five samples(data points) 
Here we are just slicing the 2d numpy array

In [9]:
print("First five columns of data: \n{}".format(iris_dataset['data'][:5]))

First five columns of data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [10]:
print("Type of target : {}".format(type(iris_dataset['target'])))

Type of target : <class 'numpy.ndarray'>


In [11]:
print("Shape of target : {}".format(iris_dataset['target'].shape))

Shape of target : (150,)


Using train_test_split we are spliting the entire data. X_train contains 75% of the rows and X_test contains the remaining. Here y denotes labels.


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state = 0)

Lets see the dataset after dividing into training and testing dataset.

In [13]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


* This is the k nearest neighbours machine learning model.
* Here we are using k nearest neighbour classification algorithm in the KNeighborsClassifier class in the neighbours module. 
Before we can use model, we need to instantiate the class into an object.

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

Training the entire model using training data
* Fit the entire k nearest neighbour classification algorithm to the X_train, y_train values

In [17]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Making Predictions 

In [19]:
X_new = np.array([[5, 2.9, 1, 0.2]])

print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


In [20]:
prediction = knn.predict(X_new)

print("Prediction: {}".format(prediction))
print("Predicted target name: {}".format(
    iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted target name: ['setosa']


## Evaluating the model
predicting the output for entire test dataset

In [21]:
y_pred = knn.predict(X_test)
print("Test set predictions: \n {}".format(y_pred))

Test set predictions: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


Checking the accuracy of the model.

In [22]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158


We got an accuracy of 0.9736842105263158